name: single_latent_overfit_test
version: debug

all_checkpoint_dir: /home/tst000/projects/checkpoint
checkpoint_dir: !ref <all_checkpoint_dir>/<name>/version_<version>/
pretrained_model: "" #!ref <all_checkpoint_dir>/<name>/version_5/epoch_00180.pth
tmp_dir: /home/tst000/projects/tmp/libriTTS

latent_path: /home/tst000/projects/datasets/LibriTTS_synthesize/wm_noise.pt

# training and dataset param
lr: 1.0e-4
train_batch_size: 32
val_batch_size: 64
epochs: 10
unsorted_batch_size: 256
allowed_padding: 50
is_train: true
steps_per_epoch: 3000


fp16: true
num_workers: 10
device: cuda
save_freq: 50
log_audio_batchs: 10

# mel param
sample_rate: 24000
n_mel_channels: 100
hop_length: 256
win_length: 1024
n_fft: 1024

# augmentation config
transform_configs:
  AddColoredNoise:
    mode: "per_example"
    p: 1.0
    min_snr_in_db: 10.0
    max_snr_in_db: 10.0

# F5TTS params
mel_spec_kwargs:
  target_sample_rate: !ref <sample_rate>
  n_mel_channels: !ref <n_mel_channels>
  hop_length: !ref <hop_length>
  win_length: !ref <win_length>
  n_fft: !ref <n_fft>
  mel_spec_type": "vocos"

train_ref_wav_file: "/home/tst000/projects/datasets/selected_ref_files_train.txt"
val_ref_wav_file: "/home/tst000/projects/datasets/selected_ref_files_eval.txt"

train_gen_txt_fname: "/home/tst000/projects/datasets/selected_gen_text_train.txt"
val_gen_txt_fname: "/home/tst000/projects/datasets/selected_gen_text_eval.txt"

training_args: !new:attrmap.AttrMap
  ema_modules: "detector"
  loss_weights:
    mel_reg_l1_loss: 1.0
    detector_loss: 1.0

train_dataloader: !apply:latent_aug_wm.datasets.mel_dataset.get_combine_dataloader
  ref_wav_file: !ref <train_ref_wav_file>
  gen_txt_fname: !ref <train_gen_txt_fname>
  mel_spec_kwargs: !ref <mel_spec_kwargs>
  tmp_dir: !ref <tmp_dir>
  shuffle: True
  unsorted_batch_size: !ref <unsorted_batch_size>
  batch_size: !ref <train_batch_size>
  allowed_padding: !ref <allowed_padding>

val_dataloader: !apply:latent_aug_wm.datasets.mel_dataset.get_combine_dataloader
  ref_wav_file: !ref <val_ref_wav_file>
  gen_txt_fname: !ref <val_gen_txt_fname>
  mel_spec_kwargs: !ref <mel_spec_kwargs>
  tmp_dir: !ref <tmp_dir>
  shuffle: False
  unsorted_batch_size: !ref <unsorted_batch_size>
  batch_size: !ref <val_batch_size>
  allowed_padding: !ref <allowed_padding>

common_latent: !apply:torch.load
  - !ref <latent_path>

noise_encoder: !new:latent_aug_wm.model.encoder.UniqueNoiseEncoder
  - !ref <common_latent>

f5tts: !new:latent_aug_wm.f5_infer.infer.F5TTSBatchInferencer
  device: !ref <device>
  train: !ref <is_train>

detector: !new:latent_aug_wm.model.decoder.BaseAudioSealClassifier
  input_dim: 1

model: !new:attrmap.AttrMap
  noise_encoder: !ref <noise_encoder>
  f5tts: !ref <f5tts>
  detector: !ref <detector>

model_ema: !new:attrmap.AttrMap
  noise_encoder: !copy <noise_encoder>
  detector: !copy <detector>

model_device: !apply:latent_aug_wm.trainer.base.Trainer.load_attr_model_to_device
  - !ref <model>
  - !ref <device>

model_ema_device: !apply:latent_aug_wm.trainer.base.Trainer.load_attr_model_to_device
  - !ref <model_ema>
  - !ref <device>

# lr schduler param
schduler_params:
  max_lr: !ref <lr>
  pct_start: 0.0
  epochs: !ref <epochs>
  steps_per_epoch: !ref <steps_per_epoch>


optimizer: !apply:nvc_net.trainer.optimizer.build_optimizer
  model_dict: !ref <model>
  scheduler_params_dict:
    noise_encoder: !copy <schduler_params>
    detector: !copy <schduler_params>

aug_applier: !new:latent_aug_wm.loss.base.AugApplier
  aug_obj: !new:latent_aug_wm.data_augmentation.base.BaseBatchAugmentation
    sampling_rate: !ref <sample_rate>
    transform_configs: !ref <transform_configs>


loss_fn: !apply:latent_aug_wm.loss.construct_loss_fn
  construct_loss_fn:
    - !name:latent_aug_wm.loss.base.generate_multiple_mel_from_f5tts
    - !name:latent_aug_wm.loss.base.mel_reg_L1_loss
    - !ref <aug_applier>
    - !name:latent_aug_wm.loss.base.detector_loss
